### PR TITLE
Format Master File Tree

### PR DESCRIPTION
**Pull request by exoad**
I moved all essential Code files and folders into a folder `/src/` this helps to clean everything clean. Everything that is not documentations, dependency configs should be in their designated folders or in the `/src/` folder. 

Not a big change.

### CODE REVIEW

**Comment by Dang-The-Vuong** [comment]
Orz

**Review by exoad — COMMENTED** [review]
signed?

**Review by Dang-The-Vuong — APPROVED** [review]
Ok

**Comment by exoad** [comment]
Ok I will just merge these

**Pull request merged**
